name: waste_managament
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # suitable with bloc
  # equatable for compares objects (with the same data are considered equal automatically)
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  # for local database
  shared_preferences: ^2.5.3
  # I use http, because i like http's api implementation
  # Retrofit It allows define API endpoints using annotations,
  http: ^1.3.0
  #
  go_router: ^14.8.1
  email_validator: ^3.0.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_app2.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icons/logo_app2.png"

  # Add flutter_gen_runner to dev_dependencies
  flutter_gen_runner: ^5.3.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  # Declare assets (required for flutter_gen to work)
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

#  fonts:
#    - family: Satoshi
#      fonts:
#        - asset: assets/fonts/Satoshi-Black.ttf
#          weight: 900
#        - asset: assets/fonts/Satoshi-Bold.ttf
#          weight: 600
#        - asset: assets/fonts/Satoshi-Light.ttf
#          weight: 500
#        - asset: assets/fonts/Satoshi-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Satoshi-Regular.ttf
#          weight: 400
#    - family: Oswald
#      fonts:
#        - asset: assets/fonts/Oswald-Regular.ttf
#          weight: 400
flutter_gen:
  output: lib/generated/
  assets:
    enabled: true
